name: ArkasteinMMO
version: '1.0-SNAPSHOT'
main: com.dark.arkasteinMMO.ArkasteinMMO
bootstrapper: com.dark.arkasteinMMO.ArkasteinMMOBootstrap
api-version: '1.21'
authors: [ Dark ]
description: The Blacktome universe functionalities in a paper plugin, including bosses, magic and more.
load: STARTUP
